stages:
  - install
  - test

install:
  image: cypress/browsers:node-20.11.1-chrome-123.0.6312.58-1-ff-124.0-edge-122.0.2365.92-1
  stage: install
  allow_failure: true

  script:
    - npm install
    - npm install --save-dev cypress@13.4.0
    - npx cypress --version

test:   
  image: cypress/browsers:node-20.11.1-chrome-123.0.6312.58-1-ff-124.0-edge-122.0.2365.92-1
  stage: test
  allow_failure: true
  script:
    - npm ci
    - npx cypress run
  after_script:
    - npm run generate-cucumber-html-report
  artifacts:
    when: always
    paths:
      - cypress/videos
      - cypress/reports
    expire_in: 30 day 
    